"""Autoincrement Track ID

Revision ID: ab98a6acd62b
Revises: fbd773e8b6ca
Create Date: 2021-05-29 12:25:03.576838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab98a6acd62b'
down_revision = 'fbd773e8b6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
